### ISSUE TITLE
Missed protein pre-training paper

### ISSUE THREAD

**Issue by GGchen1997** [RUC-GLAD/GGNN4Science#1]
Hello,

Thank you for the detailed survey. However, it seems that a piece of protein pre-training research titled "Structure-aware protein self-supervised learning" published in Bioinformatics in 2023 was overlooked. You can find the study at: https://academic.oup.com/bioinformatics/article/39/4/btad189/7117544

I would highly value the inclusion and discussion of this work in the most recent edition of the survey, if possible.

**Comment by ManlioWu** [comment]
> Hello,
> 
> Thank you for the detailed survey. However, it seems that a piece of protein pre-training research titled "Structure-aware protein self-supervised learning" published in Bioinformatics in 2023 was overlooked. You can find the study at: https://academic.oup.com/bioinformatics/article/39/4/btad189/7117544
> 
> I would highly value the inclusion and discussion of this work in the most recent edition of the survey, if possible.

Thanks for your kindly reminder. We will cite your mentioned paper when the survey is published.
